runtime: nodejs
vm: true
api_version: 1

manual_scaling:
  instances: 1

resources:
  cpu: 0.1
  memory_gb: 0.1
  disk_size_gb: 10

network:
  forwarded_ports:
  - 3000

health_check:
  enable_health_check: false

handlers:
- url: .*
  script: nothing.js

# Temporary workaround for a Cloud SDK bug.
# Ensures that node_modules directory and any .log files are not uploaded (the
# other entries are the default values for skip_files). This will skip any Unix
# hidden files (such as the .git directory)
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*/node_modules/.*$
 - ^(.*/)?.*\.log$